import type { ComposerTranslation } from "vue-i18n";
import { Checkbox, InputNumber } from "primevue";
import { Setting } from "@/composables/setup/useSettings.ts";
import FieldSelect from "@/components/forms/FieldSelect.vue";

const languages = [
    { value: 'ar_SA', label: 'العربية السعودية' },
    { value: 'ar_IQ', label: 'العربية العراق'},
    { value: 'ar_SY', label: 'العربية سوريا'},
    { value: 'az_AZ', label: 'Azərbaycan dili'},
    { value: 'bg_BG', label: 'Български'},
    { value: 'bn_BD', label: 'বাংলা (বাংলাদেশ)'},
    { value: 'id_ID', label: 'Bahasa Indonesia'},
    { value: 'ms_MY', label: 'Bahasa Melayu'},
    { value: 'ca_ES', label: 'Català'},
    { value: 'cs_CZ', label: 'Čeština'},
    { value: 'de_DE', label: 'Deutsch'},
    { value: 'da_DK', label: 'Dansk'},
    { value: 'et_EE', label: 'Eesti'},
    { value: 'en_GB', label: 'English'},
    { value: 'en_US', label: 'English (United States)'},
    { value: 'es_AR', label: 'Español (Argentina)'},
    { value: 'es_EC', label: 'Español (Ecuador)'},
    { value: 'es_CO', label: 'Español (Colombia)'},
    { value: 'es_ES', label: 'Español (España)'},
    { value: 'es_419', label: 'Español (Latinoamérica)'},
    { value: 'es_MX', label: 'Español (México)'},
    { value: 'es_VE', label: 'Español (Venezuela)'},
    { value: 'eu_ES', label: 'Euskara'},
    { value: 'fr_FR', label: 'Français'},
    { value: 'fr_CA', label: 'Français (Canada)'},
    { value: 'fr_BE', label: 'Français (Belgique)'},
    { value: 'gl_ES', label: 'Galego'},
    { value: 'el_GR', label: 'Ελληνικά'},
    { value: 'he_IL', label: 'עברית'},
    { value: 'hi_IN', label: 'हिन्दी'},
    { value: 'hr_HR', label: 'Hrvatski'},
    { value: 'hu_HU', label: 'Magyar'},
    { value: 'it_IT', label: 'Italiano'},
    { value: 'km_KH', label: 'ភាសាខ្មែរ'},
    { value: 'kn', label: 'ಕನ್ನಡ'},
    { value: 'lv_LV', label: 'Latviešu'},
    { value: 'lt_LT', label: 'Lietuvių'},
    { value: 'mn_MN', label: 'Монгол'},
    { value: 'nl_NL', label: 'Nederlands'},
    { value: 'nl_BE', label: 'Nederlands (België)'},
    { value: 'nb_NO', label: 'Norsk (Bokmål)'},
    { value: 'nn_NO', label: 'Norsk (Nynorsk)'},
    { value: 'fa_IR', label: 'فارسی'},
    { value: 'pl_PL', label: 'Polski'},
    { value: 'pt_PT', label: 'Português (Portugal)'},
    { value: 'pt_BR', label: 'Português (Brasil)'},
    { value: 'ro_RO', label: 'Română'},
    { value: 'ru_RU', label: 'Русский'},
    { value: 'sk_SK', label: 'Slovenčina'},
    { value: 'sl_SI', label: 'Slovenščina'},
    { value: 'sq_AL', label: 'Shqip'},
    { value: 'sr_RS', label: 'Српски'},
    { value: 'fi_FI', label: 'Suomi'},
    { value: 'sv_SE', label: 'Svenska'},
    { value: 'vi_VN', label: 'Tiếng Việt'},
    { value: 'th_TH', label: 'ไทย'},
    { value: 'tr_TR', label: 'Türkçe'},
    { value: 'uk_UA', label: 'Українська'},
    { value: 'ja_JP', label: '日本語'},
    { value: 'zh_CN', label: '中文 (中国)'},
    { value: 'zh_TW', label: '中文 (台湾)'},
    { value: 'ko_KR', label: '한국어'},
    { value: 'zh_HK', label: '中文 (香港)'},
    { value: 'be_BY', label: 'Беларуская'},
    { value: 'is_IS', label: 'Íslenska'},
    { value: 'eo', label: 'Esperanto'},
    { value: 'es_CL', label: 'Español (Chile)'},
]

const pdfFonts = [
    { value: 'aealarabiya', label: 'AlArabiya'},
    { value: 'aefurat', label: 'Furat'},
    { value: 'cid0cs', label: 'cid0cs (cid0cs)'},
    { value: 'cid0ct', label: 'cid0ct (cid0ct)'},
    { value: 'cid0jp', label: 'cid0jp (cid0jp)'},
    { value: 'cid0kr', label: 'cid0kr (cid0kr)'},
    { value: 'courier', label: 'Courier'},
    { value: 'dejavusans', label: 'DejaVuSans'},
    { value: 'dejavusanscondensed', label: 'DejaVuSansCondensed'},
    { value: 'dejavusansextralight', label: 'DejaVuSans-ExtraLight'},
    { value: 'dejavusansmono', label: 'DejaVuSansMono'},
    { value: 'dejavuserif', label: 'DejaVuSerif'},
    { value: 'dejavuserifcondensed', label: 'DejaVuSerifCondensed'},
    { value: 'freemono', label: 'FreeMono'},
    { value: 'freesans', label: 'FreeSans'},
    { value: 'freeserif', label: 'FreeSerif'},
    { value: 'helvetica', label: 'Helvetica'},
    { value: 'hysmyeongjostdmedium', label: 'HYSMyeongJoStd-Medium-Acro (hysmyeongjostdmedium)'},
    { value: 'kozgopromedium', label: 'KozGoPro-Medium-Acro (kozgopromedium)'},
    { value: 'kozminproregular', label: 'KozMinPro-Regular-Acro (kozminproregular)'},
    { value: 'msungstdlight', label: 'MSungStd-Light-Acro (msungstdlight)'},
    { value: 'pdfacourier', label: 'PDFACourier'},
    { value: 'pdfahelvetica', label: 'PDFAHelvetica'},
    { value: 'pdfasymbol', label: 'PDFASymbol'},
    { value: 'pdfatimes', label: 'PDFATimes'},
    { value: 'pdfazapfdingbats', label: 'PDFAZapfdingbats'},
    { value: 'stsongstdlight', label: 'STSongStd-Light-Acro (stsongstdlight)'},
    { value: 'symbol', label: 'Symbol'},
    { value: 'times', label: 'Times-Roman'},
    { value: 'zapfdingbats', label: 'ZapfDingbats'},
];

const coreThemes = [
    { value: 'aerialgreen', label: 'Aerial Green'},
    { value: 'auror', label: 'Auror'},
    { value: 'auror_dark', label: 'Dark Auror'},
    { value: 'automn', label: 'Autumn'},
    { value: 'classic', label: 'Classic'},
    { value: 'clockworkorange', label: 'Clockwork Orange'},
    { value: 'dark', label: 'Dark'},
    { value: 'darker', label: 'Darker'},
    { value: 'flood', label: 'Flood'},
    { value: 'greenflat', label: 'Green Flat'},
    { value: 'hipster', label: 'Hipster'},
    { value: 'icecream', label: 'Ice Cream'},
    { value: 'lightblue', label: 'Light Blue'},
    { value: 'midnight', label: 'Midnight'},
    { value: 'premiumred', label: 'Premium Red'},
    { value: 'purplehaze', label: 'Purple Haze'},
    { value: 'teclib', label: 'Teclib'},
    { value: 'vintage', label: 'Vintage'},
];

export function getUserPreferencesSettings($t: ComposerTranslation): Array<Setting> {
    return [
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'language',
            label: $t('settings.core.language.label', 'Language'),
            keywords: $t('settings.core.language.keywords', ''),
            field: {
                component: FieldSelect,
                props: {options: languages, optionLabel: 'label', optionValue: 'value'},
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'date_format',
            label: $t('settings.core.date_format.label', 'Date format'),
            keywords: $t('settings.core.date_format.keywords', ''),
            field: {
                component: FieldSelect,
                props: {
                    options: [
                        { label: 'YYYY-MM-DD', value: '0'},
                        { label: 'DD-MM-YYYY', value: '1'},
                        { label: 'MM-DD-YYYY', value: '2'},
                    ],
                    optionLabel: 'label', optionValue: 'value'
                },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'names_format',
            label: $t('settings.core.names_format.label', 'Names format'),
            keywords: $t('settings.core.names_format.keywords', ''),
            field: {
                component: FieldSelect,
                props: {
                    options: [
                        { label: 'Surname Firstname', value: '0'},
                        { label: 'Firstname Surname', value: '1'},
                    ],
                    optionLabel: 'label', optionValue: 'value'
                },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'number_format',
            label: $t('settings.core.number_format.label', 'Number format'),
            keywords: $t('settings.core.number_format.keywords', ''),
            field: {
                component: FieldSelect,
                props: {
                    options: [
                        { label: '1 234.56', value: '0'},
                        { label: '1,234.56', value: '1'},
                        { label: '1 234,56', value: '2'},
                        { label: '1234.56', value: '3'},
                        { label: '1234,56', value: '4'},
                    ],
                    optionLabel: 'label', optionValue: 'value'
                },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'list_limit',
            label: $t('settings.core.list_limit.label', 'Results per page'),
            keywords: $t('settings.core.list_limit.keywords', ''),
            field: {
                component: InputNumber,
                props: {
                    min: 5,
                    max: 50,
                    step: 5,
                    allowEmpty: false
                },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'backcreated',
            label: $t('settings.core.backcreated.label', 'Go to created item after creation'),
            keywords: $t('settings.core.backcreated.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'use_flat_dropdowntree',
            label: $t('settings.core.use_flat_dropdowntree.label', 'Display the tree dropdown complete name in dropdown inputs'),
            keywords: $t('settings.core.use_flat_dropdowntree.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'use_flat_dropdowntree_on_search_result',
            label: $t('settings.core.use_flat_dropdowntree_on_search_result.label', 'Display the complete name of tree dropdown in search results'),
            keywords: $t('settings.core.use_flat_dropdowntree_on_search_result.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'show_count_on_tabs',
            label: $t('settings.core.show_count_on_tabs.label', 'Show count on tabs'),
            keywords: $t('settings.core.show_count_on_tabs.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'is_ids_visible',
            label: $t('settings.core.is_ids_visible.label', 'Show item IDs'),
            keywords: $t('settings.core.is_ids_visible.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'keep_devices_when_purging_item',
            label: $t('settings.core.keep_devices_when_purging_item.label', 'Keep devices when purging an item'),
            keywords: $t('settings.core.keep_devices_when_purging_item.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'notification_to_myself',
            label: $t('settings.core.notification_to_myself.label', 'Notifications for my changes'),
            keywords: $t('settings.core.notification_to_myself.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'display_count_on_home',
            label: $t('settings.core.display_count_on_home.label', 'Results to display on home page'),
            keywords: $t('settings.core.display_count_on_home.keywords', ''),
            field: {
                component: InputNumber,
                props: {
                    min: 1,
                    max: 30,
                },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'pdffont',
            label: $t('settings.core.pdffont.label', 'PDF export font'),
            keywords: $t('settings.core.pdffont.keywords', ''),
            field: {
                component: FieldSelect,
                props: {options: pdfFonts, optionLabel: 'label', optionValue: 'value'},
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'csv_delimiter',
            label: $t('settings.core.csv_delimiter.label', 'CSV delimiter'),
            keywords: $t('settings.core.csv_delimiter.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'palette',
            label: $t('settings.core.palette.label', 'Theme'),
            keywords: $t('settings.core.palette.keywords', 'color palette skin'),
            field: {
                component: FieldSelect,
                props: {options: coreThemes, optionLabel: 'label', optionValue: 'value'},
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'page_layout',
            label: $t('settings.core.page_layout.label', 'Page layout'),
            keywords: $t('settings.core.page_layout.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'richtext_layout',
            label: $t('settings.core.richtext_layout.label', 'Rich text field layout'),
            keywords: $t('settings.core.richtext_layout.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'highcontrast_css',
            label: $t('settings.core.highcontrast_css.label', 'Enable high contrast'),
            keywords: $t('settings.core.highcontrast_css.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'timezone',
            label: $t('settings.core.timezone.label', 'Timezone'),
            keywords: $t('settings.core.timezone.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_central_tab',
            label: $t('settings.core.default_central_tab.label', 'Default homepage tab'),
            keywords: $t('settings.core.default_central_tab.keywords', 'central'),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'timeline_order',
            label: $t('settings.core.timeline_order.label', 'Timeline order'),
            keywords: $t('settings.core.timeline_order.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'show_search_form',
            label: $t('settings.core.show_search_form.label', 'Show search form above results'),
            keywords: $t('settings.core.show_search_form.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'search_pagination_on_top',
            label: $t('settings.core.search_pagination_on_top.label', 'Show search pagination above results'),
            keywords: $t('settings.core.search_pagination_on_top.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'followup_private',
            label: $t('settings.core.followup_private.label', 'Private followups by default'),
            keywords: $t('settings.core.followup_private.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'show_jobs_at_login',
            label: $t('settings.core.show_jobs_at_login.label', 'Show new tickets on the home page'),
            keywords: $t('settings.core.show_jobs_at_login.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'task_private',
            label: $t('settings.core.task_private.label', 'Private tasks by default'),
            keywords: $t('settings.core.task_private.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_requesttypes_id',
            label: $t('settings.core.default_requesttypes_id.label', 'Request sources by default'),
            keywords: $t('settings.core.default_requesttypes_id.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'task_state',
            label: $t('settings.core.task_state.label', 'Tasks state by default'),
            keywords: $t('settings.core.task_state.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'planned_task_state',
            label: $t('settings.core.planned_task_state.label', 'Planned tasks state by default'),
            keywords: $t('settings.core.planned_task_state.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'refresh_views',
            label: $t('settings.core.refresh_views.label', 'Automatically refresh data (tickets list, project kanban) in minutes.'),
            keywords: $t('settings.core.refresh_views.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'set_default_tech',
            label: $t('settings.core.set_default_tech.label', 'Pre-select me as a technician when creating a ticket'),
            keywords: $t('settings.core.set_default_tech.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'set_default_requester',
            label: $t('settings.core.set_default_requester.label', 'Pre-select me as a requester when creating a ticket'),
            keywords: $t('settings.core.set_default_requester.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'set_followup_tech',
            label: $t('settings.core.set_followup_tech.label', 'Add me as a technician when adding a ticket follow-up'),
            keywords: $t('settings.core.set_followup_tech.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'set_solution_tech',
            label: $t('settings.core.set_solution_tech.label', 'Add me as a technician when adding a ticket solution'),
            keywords: $t('settings.core.set_solution_tech.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'timeline_action_btn_layout',
            label: $t('settings.core.timeline_action_btn_layout.label', 'Action button layout'),
            keywords: $t('settings.core.timeline_action_btn_layout.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'timeline_date_format',
            label: $t('settings.core.timeline_date_format.label', 'Timeline date display'),
            keywords: $t('settings.core.timeline_date_format.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_1',
            label: $t('settings.core.priority_1.label', 'Very low priority color'),
            keywords: $t('settings.core.priority_1.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_2',
            label: $t('settings.core.priority_2.label', 'Low priority color'),
            keywords: $t('settings.core.priority_2.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_3',
            label: $t('settings.core.priority_3.label', 'Medium priority color'),
            keywords: $t('settings.core.priority_3.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_4',
            label: $t('settings.core.priority_4.label', 'High priority color'),
            keywords: $t('settings.core.priority_4.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_5',
            label: $t('settings.core.priority_5.label', 'Very high priority color'),
            keywords: $t('settings.core.priority_5.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'priority_6',
            label: $t('settings.core.priority_6.label', 'Major priority color'),
            keywords: $t('settings.core.priority_6.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'duedateok_color',
            label: $t('settings.core.duedateok_color.label', 'Due date OK color'),
            keywords: $t('settings.core.duedateok_color.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'duedatewarning_color',
            label: $t('settings.core.duedatewarning_color.label', 'Due date warning color'),
            keywords: $t('settings.core.duedatewarning_color.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'duedatewarning_less', // combine with duedatewarning_unit
            label: $t('settings.core.duedatewarning_less.label', 'Warning state threshold'),
            keywords: $t('settings.core.duedatewarning_less.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'duedatecritical_color',
            label: $t('settings.core.duedatecritical_color.label', 'Due date critical color'),
            keywords: $t('settings.core.duedatecritical_color.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'duedatecritical_less', // combine with duedatecritical_unit
            label: $t('settings.core.duedatecritical_less.label', 'Critical state threshold'),
            keywords: $t('settings.core.duedatecritical_less.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_dashboard_central',
            label: $t('settings.core.default_dashboard_central.label', 'Central dashboard'),
            keywords: $t('settings.core.default_dashboard_central.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_dashboard_assets',
            label: $t('settings.core.default_dashboard_assets.label', 'Assets dashboard'),
            keywords: $t('settings.core.default_dashboard_assets.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_dashboard_helpdesk',
            label: $t('settings.core.default_dashboard_helpdesk.label', 'Assistance dashboard'),
            keywords: $t('settings.core.default_dashboard_helpdesk.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'default_dashboard_mini_ticket',
            label: $t('settings.core.default_dashboard_mini_ticket.label', 'Mini tickets dashboard'),
            keywords: $t('settings.core.default_dashboard_mini_ticket.keywords', ''),
            field: {},
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'is_notif_enable_default',
            label: $t('settings.core.is_notif_enable_default.label', 'Enable notifications'),
            keywords: $t('settings.core.is_notif_enable_default.keywords', ''),
            field: {
                component: Checkbox,
                props: { binary: true, trueValue: '1', falseValue: '0' },
            },
        },
        {
            context: 'core',
            scope: 'global',
            category: 'default_preferences',
            name: 'toast_location',
            label: $t('settings.core.toast_location.label', 'Toast location'),
            keywords: $t('settings.core.toast_location.keywords', 'popup notifications'),
            field: {},
        },
    ];
}